name: Rust

on:
  push:
    branches: [ master, main, dev, vector2, vector3, vector4, mat2, mat3, mat4 ]
  pull_request:
    branches: [ master, main, dev, vector2, vector3, vector4, mat2, mat3, mat4 ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
